package_assets: on
embed_assets: on
javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"
  
stylesheets:
  style:
    - public/stylesheets/style.css
  notify_me:
    - public/stylesheets/notify_me.css

javascripts:
  default:
    - public/javascripts/prototype.js
    - public/javascripts/rails.js
    - public/javascripts/s2.js
    - public/javascripts/application.js
