package_assets: on
compress_assets: off
javascript_compressor: closure

javascripts:
  default:
    - public/javascripts/prototype.js
    - public/javascripts/rails.js
    - public/javascripts/s2.js
    - public/javascripts/application.js
