package_assets: on
embed_assets: datauri
javascript_compressor: yui
## =========================
## Note About the compressor:
##
## There was an issue with closure compiler who was rewriting this line of prototype.js: if (!Node) var Node = { };
## to this: Node||(Node={});
## And this fires an JS error in IE "'Node' is undefined"
## So we switched to the YUI compressor
## =========================
# javascript_compressor: closure
# compressor_options:
#   compilation_level: "SIMPLE_OPTIMIZATIONS"

stylesheets:
  style:
    - public/stylesheets/style.css
  style_ie:
    - public/stylesheets/style_ie.css

javascripts:
  default:
    - public/javascripts/prototype.js
    - public/javascripts/rails.js
    - public/javascripts/s2.js
    - public/javascripts/application.js
  admin:
    - public/javascripts/effects.js
    - public/javascripts/admin.js
    - public/javascripts/highcharts/prototype-adapter.js
    - public/javascripts/highcharts/highcharts.js
