defaults: &defaults
  api_key: 8844ec1803ffbe6501c3d7e9cfa23bf3

development:
  <<: *defaults
  lists:
    sublimevideo:
      list_id: a064dfc4b8ccd774252a2e9c9deb9244
      segment: dev
    sublimevideo_newsletter:
      list_id: a064dfc4b8ccd774252a2e9c9deb9244

test:
  <<: *defaults
  lists:
    sublimevideo:
      list_id: a064dfc4b8ccd774252a2e9c9deb9244
      segment: test
    sublimevideo_newsletter:
      list_id: a064dfc4b8ccd774252a2e9c9deb9244

staging:
  <<: *defaults
  lists:
    sublimevideo:
      list_id: a064dfc4b8ccd774252a2e9c9deb9244
      segment: staging
    sublimevideo_newsletter:
      list_id: a064dfc4b8ccd774252a2e9c9deb9244

production:
  <<: *defaults
  lists:
    sublimevideo:
      list_id: 1defd3a2fa342e3534126166f32e02d2
      segment: my.sublimevideo.net
    sublimevideo_newsletter:
      list_id: 6cc4f36f7befd39080e43b82ade6794e
