defaults: &defaults
  subdomain: jilion
  api_token: 902e80d1986be4138f3092d10ee67d468c96d9bf
  default_room: SV Dev

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
