defaults: &defaults
  api_key: 8844ec1803ffbe6501c3d7e9cfa23bf3

development:
  <<: *defaults
  list_id: a064dfc4b8ccd774252a2e9c9deb9244
  segment: dev
test:
  <<: *defaults
  list_id: a064dfc4b8ccd774252a2e9c9deb9244
  segment: test
staging:
  <<: *defaults
  list_id: a064dfc4b8ccd774252a2e9c9deb9244
  segment: staging
production:
  <<: *defaults
  list_id: 1defd3a2fa342e3534126166f32e02d2
  segment: my.sublimevideo.net
