defaults: &defaults_dev_test
  url:       https://jilion.highrisehq.com
  api_token: bf26a52fe7ea66caad3b9eca117e07bb # remy's token

# sublimevideo's credentials
defaults_stage_prod: &defaults_stage_prod
  url:       env_var
  api_token: env_var

development:
  <<: *defaults_dev_test

test:
  <<: *defaults_dev_test

staging:
  <<: *defaults_stage_prod

production:
  <<: *defaults_stage_prod
