Voxcast:
  store_dir: voxcast
  file_format_class_name: LogsFileFormat::Voxcast
Amazon::S3::Player:
  store_dir: s3/sublimevideo.player/
  hostname: sublimevideo.player
  file_format_class_name: LogsFileFormat::S3Player
Amazon::S3::Loaders:
  store_dir: s3/sublimevideo.loaders/
  hostname: sublimevideo.loaders
  file_format_class_name: LogsFileFormat::S3Loaders
Amazon::S3::Licenses:
  store_dir: s3/sublimevideo.licenses/
  hostname: sublimevideo.licenses
  file_format_class_name: LogsFileFormat::S3Licenses
  