Voxcast:
  store_dir: voxcast
  file_format_class_name: LogsFileFormat::Voxcast
CloudfrontDownload:
  store_dir: cloudfront/sublimevideo.videos/download/
  hostname: v.sublimevideo.net
  file_format_class_name: LogsFileFormat::CloudfrontDownload
  