development:
  sessions:
    default:
      database: sv-my-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: sv-my-test
      hosts:
        - localhost:27017
      options:
        retry_interval: 0
	max_retries: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        timeout: 30
        pool_size: 10
