development:
  host: localhost
  database: sublimevideo_dev
  preload_models: true

test:
  host: localhost
  database: sublimevideo_test
  preload_models: true

staging:
  database: sublimevideo_production
  username: backups
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - hurley.member0.mongohq.com
      - 10006
    - - hurley.member1.mongohq.com
      - 10006
  preload_models: true
  skip_version_check: true
  logger: false

production:
<% if ARGV.join.include? 'assets:precompile' %>
  # make rake asset:precompile work
  preload_models: false
  host: localhost
  database: sublimevideo_production
<% else %>
  database: sublimevideo_production
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - hurley.member0.mongohq.com
      - 10006
    - - hurley.member1.mongohq.com
      - 10006
  preload_models: true
  skip_version_check: true
  logger: false
  op_timeout: 15
  connect_timeout: 15
<% end %>
