development:
  host: localhost
  database: sublimevideo_dev
  preload_models: true

test:
  host: localhost
  database: sublimevideo_test
  preload_models: true

staging:
  database: sublimevideo-staging
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - sublimevideo.member0.mongolayer.com
      - 27017
    - - sublimevideo.member1.mongolayer.com
      - 27017
    - - sublimevideo.member2.mongolayer.com
      - 27017
  preload_models: true
  logger: false

production:
<% if ARGV.join.include? 'assets:precompile' %>
  # make rake asset:precompile work
  preload_models: false
  host: localhost
  database: sublimevideo
<% else %>
  database: sublimevideo
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - sublimevideo.member0.mongolayer.com
      - 27017
    - - sublimevideo.member1.mongolayer.com
      - 27017
    - - sublimevideo.member2.mongolayer.com
      - 27017
  preload_models: true
  logger: false
<% end %>
