development:
  host: localhost
  database: sublimevideo_dev
  preload_models: true

test:
  host: localhost
  database: sublimevideo_test
  preload_models: true

staging:
  database: 'sublimevideo-stats'
  username: backups
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  host: sublimevideo.member0.mongolayer.com
  port: 27017
  preload_models: true
  skip_version_check: true
  logger: false
  op_timeout: 30
  connect_timeout: 30
  pool_size: 10

production:
<% if ARGV.join.include? 'assets:precompile' %>
  # make rake asset:precompile work
  preload_models: false
  host: localhost
  database: sublimevideo-stats
<% else %>
  database: 'sublimevideo-stats'
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  host: sublimevideo.member0.mongolayer.com
  port: 27017
  preload_models: true
  skip_version_check: true
  logger: false
  op_timeout: 30
  connect_timeout: 30
  pool_size: 10
<% end %>
