development:
  sessions:
    default:
      database: sv-my-development
      hosts:
        - localhost:27017
      options:
        preload_models: true
        use_utc: true
test:
  sessions:
    default:
      database: sv-my-test
      hosts:
        - localhost:27017
      options:
        preload_models: true
        retry_interval: 0
        max_retries: 1
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        identity_map_enabled: false
        skip_version_check: true
        preload_models: true
        pool_size: 10
        use_utc: true
        safe: true
