development:
  host: localhost
  database: mysublime

test:
  host: localhost
  database: msv_test

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>
  host: localhost
  persist_in_safe_mode: true

production:
<% if ENV['MONGOHQ_URL'] %>
  uri: <%= ENV['MONGOHQ_URL'] %>
<% else %>
  # make rake asset:precompile work
  host: localhost
  database: mysublime
<% end %>
  persist_in_safe_mode: true
  logger: false
