development:
  host: localhost
  database: sublimevideo_dev

test:
  host: localhost
  database: sublimevideo_test

staging:
  database: sublimevideo-staging
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - sublimevideo.member0.mongolayer.com
      - 27017
    - - sublimevideo.member1.mongolayer.com
      - 27017
    - - sublimevideo.member2.mongolayer.com
      - 27017
  max_retries_on_connection_failure: 3
  logger: false

production:
<% if ENV['MONGOHQ_USERNAME'] %>
  database: sublimevideo
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - sublimevideo.member0.mongolayer.com
      - 27017
    - - sublimevideo.member1.mongolayer.com
      - 27017
    - - sublimevideo.member2.mongolayer.com
      - 27017
  max_retries_on_connection_failure: 3
  logger: false
<% else %>
  # make rake asset:precompile work
  host: localhost
  database: sublimevideo
<% end %>
