defaults: &defaults
  signature_encryptor: sha512
  created_after_10_may_2010: true
  currency: USD


development:
  <<: *defaults
  login:     jilion
  user:      sublime
  password:  WWQMNC89
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_out: 7Powerhouse!MacBook@Pro2an9All-Around

test:
  <<: *defaults
  login:     jilion
  user:      sublime
  password:  WWQMNC89
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_out: 7Powerhouse!MacBook@Pro2an9All-Around

staging:
  <<: *defaults
  login:     jilion
  user:      sublime
  password:  WWQMNC89
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_out: 7Powerhouse!MacBook@Pro2an9All-Around

production:
  <<: *defaults
  login:         <%= ENV['OGONE_LOGIN'] %> # jilionPROD
  user:          <%= ENV['OGONE_USER'] %> # sublime_api
  password:      <%= ENV['OGONE_PASSWORD'] %> # "F$WZe7,2>h5%6*3g"
  signature:     <%= ENV['OGONE_SIGNATURE'] %> # "qI{No5w^R,Ee72Gi98DT#x)MV"
  signature_out: <%= ENV['OGONE_SIGNATURE_OUT'] %> # "iQuMX'!lxe34hDW7`6#mkz1_C"
