development:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_encryptor: sha512
  created_after_10_may_2010: true
  currency: USD
test:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_encryptor: sha512
  created_after_10_may_2010: true
  currency: USD
staging:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_encryptor: sha512
  created_after_10_may_2010: true
  currency: USD
production:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_encryptor: sha512
  created_after_10_may_2010: true
  currency: USD
