development:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
test:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
production:
  login:     "jilion"
  user:      "sublime"
  password:  "WWQMNC89"
  # signature: "my_ogone_sha1_signature" # extra security, only if you configured your Ogone environment so