defaults: &defaults
  signature_encryptor: sha512
  created_after_10_may_2010: true
  currency: USD

development:
  <<: *defaults
  login:     jilion
  user:      sublime
  password:  WWQMNC89
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_out: 7Powerhouse!MacBook@Pro2an9All-Around

test:
  <<: *defaults
  login:     jilion
  user:      sublime
  password:  WWQMNC89
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_out: 7Powerhouse!MacBook@Pro2an9All-Around

staging:
  <<: *defaults
  login:     jilion
  user:      sublime
  password:  WWQMNC89
  signature: MacBook@Pro2an9All-Around7Powerhouse!
  signature_out: 7Powerhouse!MacBook@Pro2an9All-Around

production:
  <<: *defaults
  login:         heroku_env
  user:          heroku_env
  password:      heroku_env
  signature:     heroku_env
  signature_out: heroku_env
