access_key: '7cc07330-5147-11df-b458-12313d01b992'
secret_key: 'Qm5HD/dosWFeL2wleFy9ppn822tpfVQ2l8h5Tlvc'
cloud_id: '96e7d5067cc367c32bfadbe885976883'
api_host: 'api.pandastream.com'
# api_host: "api.eu.pandastream.com" # for EU accounts