development:
  access_key_id:     AKIAJ2FJVCFJW3RZRUUQ
  secret_access_key: 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
test:
  access_key_id:     AKIAJ2FJVCFJW3RZRUUQ
  secret_access_key: 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
staging:
  access_key_id:     AKIAJ2FJVCFJW3RZRUUQ
  secret_access_key: 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
production:
  access_key_id:     heroku_env
  secret_access_key: heroku_env
