development:
  licenses: dev.sublimevideo.licenses
  loaders:  dev.sublimevideo.loaders
  player:   dev.sublimevideo.player
  logs:     dev.sublimevideo.logs
test:
  licenses: dev.sublimevideo.licenses
  loaders:  dev.sublimevideo.loaders
  player:   dev.sublimevideo.player
  logs:     dev.sublimevideo.logs
production:
  licenses: sublimevideo.licenses
  loaders:  sublimevideo.loaders
  player:   sublimevideo.player
  logs:     sublimevideo.logs
