development:
  licenses: dev.sublimevideo.licences
  loaders:  dev.sublimevideo.loaders
  player:   dev.sublimevideo.player
  videos:   dev.sublimevideo.videos
  panda:    dev.sublimevideo.panda
  logs:     dev.sublimevideo.logs
test:
  licenses: dev.sublimevideo.licence
  loaders:  dev.sublimevideo.loaders
  player:   dev.sublimevideo.player
  videos:   dev.sublimevideo.videos
  panda:    dev.sublimevideo.panda
  logs:     dev.sublimevideo.logs
production:
  licenses: sublimevideo.licences
  loaders:  sublimevideo.loaders
  player:   sublimevideo.player
  videos:   sublimevideo.videos
  panda:    sublimevideo.panda
  logs:     sublimevideo.logs
