# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
# :verbose: true
:concurrency: 50
:require: '.'
:timeout: 60
:queues:
  - [loader, 100]
  - [low, 100]
  - [mailer, 200]
  - [default, 500]
  - [high, 1000]
  - [one_time, 500]
  - [video_tags_migration, 1]
