# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:require: '.'
:timeout: 60
:queues:
  - ['default', 1]
  - ['my-stats_migration', 1]
  - ['my-loader', 1]
  - ['my-low', 1]
  - ['my-mailer', 2]
  - ['my', 5]
  - ['my-high', 10]
