# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: true
:concurrency:  50
:require: '.'
:timeout: 8
:queues:
  - [low, 1]
  - [mailer, 2]
  - [default, 5]
  - [high, 10]
