defaults: &defaults
  base_url: http://jilion.zendesk.com
  username: zeno@jilion.com
  password: wrank8

development:
  <<: *defaults
  
test:
  <<: *defaults
  
staging:
  <<: *defaults
  
production:
  base_url: <%= ENV['ZENDESK_URL'] %>
  username: <%= ENV['ZENDESK_USERNAME'] %>
  password: <%= ENV['ZENDESK_PASSWORD'] %>
