defaults: &defaults
  base_url: http://jilion.zendesk.com
  username: zendesk@sublimevideo.net
  password: wrank8

# sublimevideo's credentials
defaults_stage_prod: &defaults_stage_prod
  base_url: heroku_env
  username: heroku_env
  password: heroku_env

development:
  <<: *defaults
  
test:
  <<: *defaults
  
staging:
  <<: *defaults_stage_prod
  
production:
  <<: *defaults_stage_prod
