defaults: &defaults
  base_url: http://jilion.zendesk.com
  username: zeno@jilion.com
  password: wrank8

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
