defaults: &defaults
  base_url: http://jilion.zendesk.com
  username: zendesk@sublimevideo.net
  password: wrank8

development:
  <<: *defaults
  
test:
  <<: *defaults
  
staging:
  <<: *defaults
  
production:
  base_url: http://jilion.zendesk.com # <%= ENV['ZENDESK_URL'] %>
  username: zendesk@sublimevideo.net # <%= ENV['ZENDESK_USERNAME'] %>
  password: wrank8 # <%= ENV['ZENDESK_PASSWORD'] %>
