defaults: &defaults
  base_url: <%= ENV['ZENDESK_URL'] %> # http://jilion.zendesk.com
  username: <%= ENV['ZENDESK_USERNAME'] %> # zeno@jilion.com
  password: <%= ENV['ZENDESK_PASSWORD'] %> # wrank8

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
